package de.viadee.patterns.behavioral.templatemethod.classic;

import java.util.Arrays;
import java.util.List;

public class BandRehearsalClassic {

	public static void main(String[] args) {
		GuitarPlayer guitarPlayer = new GuitarPlayer();
		Singer singer = new Singer();
		List<Musician> band = Arrays.asList(guitarPlayer, singer);

		for (Musician musician : band) {
			musician.performRehearsal();
		}

		// driving to rehearsal...
		// connecting guitar to amp...
		// playing guitar...
		// complaining about bass player...
		// playing guitar...
		// driving home...
		//
		//
		// driving to rehearsal...
		// turning on mic...
		// singing...
		// complaining about bass player...
		// singing...
		// driving home...

	}

}
